// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGaUw9OSWIZSpRZoOJOJO3sv_zIo481DY',
    appId: '1:720485656307:web:90729a1f23791224bf7986',
    messagingSenderId: '720485656307',
    projectId: 'learnrealtimedatabase-e3301',
    authDomain: 'learnrealtimedatabase-e3301.firebaseapp.com',
    storageBucket: 'learnrealtimedatabase-e3301.appspot.com',
    measurementId: 'G-MY6QJRQ5SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiovMO-ZVp9S57pmikeQixQ0UuKXpq8_U',
    appId: '1:720485656307:android:2da2899eb5950c12bf7986',
    messagingSenderId: '720485656307',
    projectId: 'learnrealtimedatabase-e3301',
    storageBucket: 'learnrealtimedatabase-e3301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMnU4E7Eo0x3trxj7s9BOiqHibKdGNXM',
    appId: '1:720485656307:ios:182f760ba3b3e983bf7986',
    messagingSenderId: '720485656307',
    projectId: 'learnrealtimedatabase-e3301',
    storageBucket: 'learnrealtimedatabase-e3301.appspot.com',
    iosBundleId: 'com.example.realtimeDatabaseCrud',
  );
}
